server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/tmp?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                use_sql_comments: true
        show-sql: true
alibaba:
    cloud:
        access-key: LTAI5t68NnuV4S3ypSKpxNeY
        bucket-name: sms-11
        oss:
            endpoint: oss-cn-hangzhou.aliyuncs.com
        secret-key: Tvbhb3DhvEdnSSw8QRuvzdHJQ57BOM
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
