#
server:
    port: 8080
#
spring:
    # MySQL
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/tmp?useSSL=false
        username: root
    # JPA, Hibernate
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                use_sql_comments: true
        show-sql: true
    servlet:
        # MultipartFile upload configuration
        multipart:
            # single file max size
            max-file-size: 50MB
            # single request ... (一次请求可以上传多个文件)
            max-request-size: 200MB
alibaba:
    cloud:
        access-key: LTAI5t68NnuV4S3ypSKpxNeY
        bucket-name: sms-11
        oss:
            endpoint: oss-cn-hangzhou.aliyuncs.com
        secret-key: Tvbhb3DhvEdnSSw8QRuvzdHJQ57BOM
# Mybatis
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true